trigger:
  - expansion

pool:
  vmImage: 'ubuntu-latest'

steps:

# 1. Checkout source code
- checkout: self

# 2. Install Node.js
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '20.x'

# 3. Install npm dependencies
- task: PowerShell@2
  displayName: 'Install dependencies'
  inputs:
    targetType: 'inline'
    script: |
      npm ci
    workingDirectory: '$(Build.SourcesDirectory)'

# 4. Run Playwright tests on Microsoft Playwright Workspaces
- task: AzureCLI@2
  displayName: 'Run Playwright Tests'
  inputs:
    azureSubscription: 'playwrightTesting'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Write-Host "Azure account:"
      az account show

      Write-Host "Running Playwright tests..."
      npx playwright test --config=playwright.service.config.ts --workers=20
    addSpnToEnvironment: true
    workingDirectory: '$(Build.SourcesDirectory)'
  env:
    PLAYWRIGHT_SERVICE_URL: $(PLAYWRIGHT_SERVICE_URL)

# 5. Publish Playwright HTML report
- task: PublishPipelineArtifact@1
  displayName: 'Upload Playwright Report'
  condition: always()
  inputs:
    targetPath: '$(Build.SourcesDirectory)/playwright-report'
    artifact: 'Playwright-Report'
    publishLocation: 'pipeline'